#spring:
#  profiles:
#    include: devDB,devRedis,devMVC
#    active: dev

#
#spring:
#  profiles:
#    include: devRedis,devDB,devMVC
#    active: dev


spring:
  profiles:
    active: dev
    include: devMVC,devRedis,devDB
